services:
  javascript-app:
    build:
      context: .
    container_name: javascript-app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "3000:3000"  # Expose Next.js app on port 3000
    networks:
      - appnet
    # No volumes needed as this is a stateless web app

networks:
  appnet:
    driver: bridge
